quarkus.http.port=8090
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:./task5;INIT=RUNSCRIPT FROM 'classpath:schema-h2-v2.sql'
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true

# Hibernate settings to ensure sequential IDs
quarkus.hibernate-orm.unsupported-properties."hibernate.id.new_generator_mappings"=true
quarkus.hibernate-orm.unsupported-properties."hibernate.id.optimizer.pooled.preferred"=none

# Test configuration
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:testdb;INIT=RUNSCRIPT FROM 'classpath:schema-h2-v2.sql'
%test.quarkus.hibernate-orm.database.generation=drop-and-create
